### ISSUE TITLE
using with cowboy

### ISSUE THREAD

**Issue by fiodinggo** [choptastic/sql_bridge#6]
how can i using sql_bridge module in cowboy framework?

**Comment by manuel-rubio** [comment]
@fiodinggo I think your question isn't fit here. You can use cowboy and sql_bridge independently, there is no a single way to use them together.

**Comment by choptastic** [comment]
Thanks for answering Manuel.  Yes, they are unrelated libraries.  SQL Bridge is for talking to a database, while Cowboy is for handling web requests. 

If you're looking for a way to use SQL Bridge and Cowboy in the same project together, then I suggest looking at [Nitrogen](http://nitrogenproject.com) (which has Cowboy as a backend option), and SQL Bridge was largely designed to work as a database backend for Nitrogen Applications.

**Comment by fiodinggo** [comment]
ok, thanx a lot for u'r suggest.,
